// <auto-generated />
namespace FLAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class VaultsGameId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VaultsGameId));
        
        string IMigrationMetadata.Id
        {
            get { return "202106032257246_Vaults.GameId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
