// <auto-generated />
namespace FLAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class M2MTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M2MTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202105272324128_M2MTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
